// <auto-generated />
using System;
using FitZone.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitZone.Repository.Migrations
{
    [DbContext(typeof(FitContext))]
    [Migration("20260628155219_AddBotChatHistory")]
    partial class AddBotChatHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitZone.Core.Entitys.Chat.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BotConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BotRole")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ChatType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "BotConversationId")
                        .HasDatabaseName("IX_ChatMessages_BotSession")
                        .HasFilter("[BotConversationId] IS NOT NULL");

                    b.HasIndex("SenderId", "ReceiverId", "ChatType")
                        .HasDatabaseName("IX_ChatMessages_HumanChat");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ClientNutritionConstraints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdherenceThresholdPercent")
                        .HasColumnType("int");

                    b.Property<bool>("ApplyTrainingWeekNoiseCorrection")
                        .HasColumnType("bit");

                    b.Property<int>("CalorieCeiling")
                        .HasColumnType("int");

                    b.Property<int>("CalorieFloor")
                        .HasColumnType("int");

                    b.Property<decimal>("DeviationTriggerKg")
                        .HasColumnType("decimal(5,3)");

                    b.Property<bool>("EnableBaselineRecalibrationReview")
                        .HasColumnType("bit");

                    b.Property<bool>("EnergyLevelEscalationRule")
                        .HasColumnType("bit");

                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedWeeklyChangeMax")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("ExpectedWeeklyChangeMin")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("FatFloorG")
                        .HasColumnType("int");

                    b.Property<int>("MaxCumulativeDriftKcal")
                        .HasColumnType("int");

                    b.Property<int>("MaxSingleAdjustmentKcal")
                        .HasColumnType("int");

                    b.Property<int>("PreferredAdjustmentVector")
                        .HasColumnType("int");

                    b.Property<bool>("PreserveLeanMassOverRate")
                        .HasColumnType("bit");

                    b.Property<int>("ProteinFloorG")
                        .HasColumnType("int");

                    b.Property<bool>("RequireConsecutiveWeeksDeviation")
                        .HasColumnType("bit");

                    b.Property<int>("WeightAveragingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentID")
                        .IsUnique();

                    b.ToTable("ClientNutritionConstraints", t =>
                        {
                            t.HasCheckConstraint("CK_Constraints_Adherence", "[AdherenceThresholdPercent] >= 0 AND [AdherenceThresholdPercent] <= 100");

                            t.HasCheckConstraint("CK_Constraints_WeightAveragingDays", "[WeightAveragingDays] IN (3, 5, 7)");
                        });
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Coachs", t =>
                        {
                            t.HasCheckConstraint("CK_Coach_Rating", "[Rating] >= 0 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("FitZone.Core.Entitys.DayProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarbTargetG")
                        .HasColumnType("int");

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DayProtocolType")
                        .HasColumnType("int");

                    b.Property<int>("FatTargetG")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedWorkoutSessionID")
                        .HasColumnType("int");

                    b.Property<int>("NutritionWeekID")
                        .HasColumnType("int");

                    b.Property<int>("ProteinTargetG")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCaloriesTarget")
                        .HasColumnType("int");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedWorkoutSessionID");

                    b.HasIndex("NutritionWeekID");

                    b.ToTable("DayProtocols");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("CommonMistakes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryMuscles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryMuscles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CarbPer100g")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CoachID")
                        .HasColumnType("int");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("IsWhole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("ServingSizeG")
                        .HasColumnType("int");

                    b.Property<string>("ServingSizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachID");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayProtocolID")
                        .HasColumnType("int");

                    b.Property<int>("MealOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int");

                    b.Property<int>("TargetCarbG")
                        .HasColumnType("int");

                    b.Property<int>("TargetFatG")
                        .HasColumnType("int");

                    b.Property<int>("TargetProteinG")
                        .HasColumnType("int");

                    b.Property<int?>("TimeFromTrainingMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TimingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayProtocolID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MealFoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountGrams")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("FoodItemID")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<int?>("SwapGroupID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemID");

                    b.HasIndex("MealID");

                    b.ToTable("MealFoodItems");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbsoluteCalorieTarget")
                        .HasColumnType("int");

                    b.Property<int>("CalorieStrategyType")
                        .HasColumnType("int");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationOnWeeks")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedWorkoutProgramID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinTargetPerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TDEEAdjustmentKcal")
                        .HasColumnType("int");

                    b.Property<int>("TrainingGoal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachID");

                    b.HasIndex("LinkedWorkoutProgramID");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalorieModifier")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("FocusNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextWeekPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutritionPlanID")
                        .HasColumnType("int");

                    b.Property<string>("ProgressionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("WeekProtocolType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanID");

                    b.ToTable("NutritionWeeks");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.PaymentEntity.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FocusArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextWeekPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("ProgramWeeks");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.SessionExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderInSection")
                        .HasColumnType("int");

                    b.Property<int?>("RPETarget")
                        .HasColumnType("int");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Tempo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TraineeMemberships");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeNutritionEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaselineCalories")
                        .HasColumnType("int");

                    b.Property<int>("CurrentAdjustedKcal")
                        .HasColumnType("int");

                    b.Property<int?>("EmpiricalTDEEKcal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedWorkoutEnrollmentID")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeekUnlocked")
                        .HasColumnType("int");

                    b.Property<int>("NutritionPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraineeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedWorkoutEnrollmentID");

                    b.HasIndex("NutritionPlanID");

                    b.HasIndex("TraineeID", "NutritionPlanID", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TraineeNutritionEnrollments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeProgramEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxWeekUnlocked")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("WorkoutProgramId");

                    b.HasIndex("TraineeId", "TrackId", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TraineeProgramEnrollments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WeeklyCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdherencePercent")
                        .HasColumnType("int");

                    b.Property<int?>("AppliedAdjustmentVector")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageWeight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ClientNote")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("CoachApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CoachDecision")
                        .HasColumnType("int");

                    b.Property<string>("CoachNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CoachNoteAction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CoachReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<int?>("FinalAdjustmentKcal")
                        .HasColumnType("int");

                    b.Property<int>("HungerLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("MorningWeight1")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MorningWeight2")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MorningWeight3")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("NoteCategory")
                        .HasColumnType("int");

                    b.Property<string>("ProjectedOutcomeIfNoAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemConfidence")
                        .HasColumnType("int");

                    b.Property<int?>("SystemProposalKcal")
                        .HasColumnType("int");

                    b.Property<string>("SystemProposalReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentID", "WeekNumber")
                        .IsUnique();

                    b.ToTable("WeeklyCheckIns", t =>
                        {
                            t.HasCheckConstraint("CK_CheckIn_Adherence", "[AdherencePercent] >= 0 AND [AdherencePercent] <= 100");

                            t.HasCheckConstraint("CK_CheckIn_EnergyLevel", "[EnergyLevel] >= 1 AND [EnergyLevel] <= 5");

                            t.HasCheckConstraint("CK_CheckIn_HungerLevel", "[HungerLevel] >= 1 AND [HungerLevel] <= 5");

                            t.HasCheckConstraint("CK_CheckIn_SleepQuality", "[SleepQuality] >= 1 AND [SleepQuality] <= 5");
                        });
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationOnWeeks")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsDuration")
                        .HasColumnType("int");

                    b.Property<int>("SessionsPerWeeks")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingGoal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("TrackId");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CooldownNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("PrimerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramWeekId")
                        .HasColumnType("int");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarmupNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramWeekId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Chat.ChatMessage", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ClientNutritionConstraints", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.TraineeNutritionEnrollment", "Enrollment")
                        .WithOne("Constraints")
                        .HasForeignKey("FitZone.Core.Entitys.ClientNutritionConstraints", "EnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("Coach")
                        .HasForeignKey("FitZone.Core.Entitys.Coach", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.DayProtocol", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.WorkoutSession", "LinkedWorkoutSession")
                        .WithMany()
                        .HasForeignKey("LinkedWorkoutSessionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitZone.Core.Entitys.NutritionWeek", "NutritionWeek")
                        .WithMany("DayProtocols")
                        .HasForeignKey("NutritionWeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedWorkoutSession");

                    b.Navigation("NutritionWeek");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Exercise", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Coach", "Coach")
                        .WithMany("Exercises")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.FoodItem", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Meal", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.DayProtocol", "DayProtocol")
                        .WithMany("Meals")
                        .HasForeignKey("DayProtocolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayProtocol");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MealFoodItem", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.FoodItem", "FoodItem")
                        .WithMany("MealFoodItems")
                        .HasForeignKey("FoodItemID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Meal", "Meal")
                        .WithMany("MealFoodItems")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MembershipPlan", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Membership", "Membership")
                        .WithMany("MembershipPlans")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionPlan", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.WorkoutProgram", "LinkedWorkoutProgram")
                        .WithMany()
                        .HasForeignKey("LinkedWorkoutProgramID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");

                    b.Navigation("LinkedWorkoutProgram");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionWeek", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.NutritionPlan", "NutritionPlan")
                        .WithMany("NutritionWeeks")
                        .HasForeignKey("NutritionPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.PaymentEntity.Payment", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.MembershipPlan", "MembershipPlan")
                        .WithMany("Payments")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramWeek", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramWeeks")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.SessionExercise", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("Trainee")
                        .HasForeignKey("FitZone.Core.Entitys.Trainee", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeMembership", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Trainee", "Trainee")
                        .WithMany("TraineeMemberships")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeNutritionEnrollment", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.TraineeProgramEnrollment", "LinkedWorkoutEnrollment")
                        .WithMany()
                        .HasForeignKey("LinkedWorkoutEnrollmentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FitZone.Core.Entitys.NutritionPlan", "NutritionPlan")
                        .WithMany("TraineeNutritionEnrollments")
                        .HasForeignKey("NutritionPlanID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LinkedWorkoutEnrollment");

                    b.Navigation("NutritionPlan");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeProgramEnrollment", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Trainee", "Trainee")
                        .WithMany("TraineeProgramEnrollments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.WorkoutProgram", "WorkoutProgram")
                        .WithMany("TraineeProgramEnrollments")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("Trainee");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WeeklyCheckIn", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.TraineeNutritionEnrollment", "Enrollment")
                        .WithMany("WeeklyCheckIns")
                        .HasForeignKey("EnrollmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutProgram", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Coach", "Coach")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Track", "Track")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutSession", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.ProgramWeek", "ProgramWeek")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("ProgramWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramWeek");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.DayProtocol", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Exercise", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.FoodItem", b =>
                {
                    b.Navigation("MealFoodItems");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Coach")
                        .IsRequired();

                    b.Navigation("Payments");

                    b.Navigation("Trainee")
                        .IsRequired();
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Meal", b =>
                {
                    b.Navigation("MealFoodItems");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Membership", b =>
                {
                    b.Navigation("MembershipPlans");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MembershipPlan", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionPlan", b =>
                {
                    b.Navigation("NutritionWeeks");

                    b.Navigation("TraineeNutritionEnrollments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.NutritionWeek", b =>
                {
                    b.Navigation("DayProtocols");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramWeek", b =>
                {
                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Track", b =>
                {
                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.Navigation("TraineeMemberships");

                    b.Navigation("TraineeProgramEnrollments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeNutritionEnrollment", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("WeeklyCheckIns");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutProgram", b =>
                {
                    b.Navigation("ProgramWeeks");

                    b.Navigation("TraineeProgramEnrollments");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.WorkoutSession", b =>
                {
                    b.Navigation("SessionExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
