// <auto-generated />
using System;
using FitZone.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitZone.Repository.Data.Migrations
{
    [DbContext(typeof(FitContext))]
    [Migration("20260109125902_InheritFromBaseEntity")]
    partial class InheritFromBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitZone.Core.Entitys.BaseProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasePrograms");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Coachs", t =>
                        {
                            t.HasCheckConstraint("CK_Coach_Rating", "[Rating] >= 0 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Membership", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MembershipPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<int>("MembershipID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MembershipID");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramDays", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramTemplateID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramTemplateID");

                    b.ToTable("ProgramDays");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BaseProgramID")
                        .HasColumnType("int");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BaseProgramID");

                    b.HasIndex("CoachID");

                    b.ToTable("ProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeMembership", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MembershipID")
                        .HasColumnType("int");

                    b.Property<int>("MembershipPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MembershipID");

                    b.HasIndex("MembershipPlanID");

                    b.HasIndex("TraineeID");

                    b.ToTable("TraineeMemberships");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeProgramTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProgramTemplateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramTemplateID");

                    b.HasIndex("TraineeID", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TraineeProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("FitZone.Core.Entitys.Coach", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.MembershipPlan", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Membership", "Membership")
                        .WithMany("MembershipPlans")
                        .HasForeignKey("MembershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramDays", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.ProgramTemplate", "ProgramTemplate")
                        .WithMany("ProgramDays")
                        .HasForeignKey("ProgramTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramTemplate");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramTemplate", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.BaseProgram", "BaseProgram")
                        .WithMany("ProgramTemplates")
                        .HasForeignKey("BaseProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Coach", "Coach")
                        .WithMany("ProgramTemplates")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseProgram");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.User", "User")
                        .WithOne("Trainee")
                        .HasForeignKey("FitZone.Core.Entitys.Trainee", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeMembership", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.Membership", null)
                        .WithMany("TraineeMemberships")
                        .HasForeignKey("MembershipID");

                    b.HasOne("FitZone.Core.Entitys.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Trainee", "Trainee")
                        .WithMany("TraineeMemberships")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.TraineeProgramTemplate", b =>
                {
                    b.HasOne("FitZone.Core.Entitys.ProgramTemplate", "ProgramTemplate")
                        .WithMany("TraineeProgramTemplates")
                        .HasForeignKey("ProgramTemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitZone.Core.Entitys.Trainee", "Trainee")
                        .WithMany("TraineeProgramTemplates")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramTemplate");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.BaseProgram", b =>
                {
                    b.Navigation("ProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Coach", b =>
                {
                    b.Navigation("ProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Membership", b =>
                {
                    b.Navigation("MembershipPlans");

                    b.Navigation("TraineeMemberships");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.ProgramTemplate", b =>
                {
                    b.Navigation("ProgramDays");

                    b.Navigation("TraineeProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.Trainee", b =>
                {
                    b.Navigation("TraineeMemberships");

                    b.Navigation("TraineeProgramTemplates");
                });

            modelBuilder.Entity("FitZone.Core.Entitys.User", b =>
                {
                    b.Navigation("Coach")
                        .IsRequired();

                    b.Navigation("Trainee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
